config/routes.rb
Djobs::Application.routes.draw do
resources :jobs
root 'jobs#index'

  

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, presence: true
	validates :company, presence: true
	validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  	@jobs = Job.page(params[:page]).per(25)
  end

  def new
  	@job =Job.new
  end


	def create
		@job =Job.new(params.require(:job).permit(:title, :company, :url))
		if @job.save
			redirect_to root_path
		else
			render "new"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<div class="main">
<h1>Djobs</h1>
<p>Le site d'emploi simple, <u>très simple</u></p>
</div>

<div class="container">
	<div class="row">
		<% @jobs.each do |job| %>
		<div class="job col-xs-6 col-sm-3">
		<h3 class="created">Paru le <%= job.created_at %></h3>
		<h2><%= link_to job.title, job.url %></h2>
		<h2><%= job.company %></h2>
		</div>
		<% end %>
	</div>
</div>

<div class="link">
<p><%= link_to "Ajoutez un job", new_job_path %></p>
<p><%= paginate @jobs %></p>
</div>

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>

<%= simple_form_for @job do |form| %>
<%= form.input :title, label: "Job title" %>
<%= form.input :company, label: "Your company" %>
<%= form.input :url, label: "Link to job" %>
<%= form.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Djobs</title>

	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Comfortaa:400,300|Open+Sans:400,300' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>